# Server Configuration
server:
  port: 8081

# Spring Security OAuth2 Resource Server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/anhto
          jwk-set-uri: http://localhost:8080/realms/anhto/protocol/openid-connect/certs

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/kcuserprovider
    username: postgres
    password: Tuan3010

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Application Name
  application:
    name: keycloak-backend

# Keycloak Configuration
keycloak:
  server-url: http://localhost:8080
  realm: anhto
  client-id: anhto_client
  client-secret: ehQRbXKaq9BUFOPFGjwXLtQVAK8P07cd
  admin-username: admin
  admin-password: Tuan3010

# Logging (optional)
logging:
  level:
    com.anhto.keycloak: DEBUG
    org.springframework.security: DEBUG